Cleanup and add make everything functional
ThePrez/WatsonX-SDK-Db2-IBMi pull request #2
Opened 2024-08-06 18:20 UTC by worksofliam

* Seperates logic into units
* Added test cases

2024-08-06 18:32 UTC, ThePrez requested changes

2024-08-06 18:32 UTC, ThePrez commented on src/install.sql
> +  set watsonx.JobTokenExpires = current timestamp + expires seconds;
Need a buffer (recommended minimum 60 seconds) here (gross)

2024-08-06 18:34 UTC, worksofliam commented on src/install.sql
> +  set watsonx.JobTokenExpires = current timestamp + expires seconds;
Done

2024-08-06 19:11 UTC, forstie commented on src/auth.sql
> +  renew:
what's this for? Sort of looks like what I coded for JG, but its not used in this coding

2024-08-06 19:14 UTC, forstie commented on src/auth.sql
> +  returns char(1) ccsid 1208
There could be a continue handler or exit handler for unexpected errors that returns N.

2024-08-06 19:15 UTC, forstie commented on src/generate.sql
> +  not deterministic
no external action
set option usrprf = *user, dynusrprf = *user, commit = *none

2024-08-06 19:18 UTC, forstie commented on src/install.sql
> +create or replace variable watsonx.apikey varchar(100)  default '';
control the ccsid or use for sbcs data

2024-08-06 19:18 UTC, forstie commented on src/install.sql
> +create or replace variable watsonx.JobBearerToken varchar(10000) default null;
control the ccsid or use for sbcs data

2024-08-06 19:20 UTC, forstie commented on src/install.sql
> +create or replace procedure watsonx.SetApiKeyForJob(apikey varchar(100))
Do you care about performance?

If yes, then change all procedures to use PROGRAM TYPE SUB

2024-08-06 19:20 UTC, forstie commented on src/install.sql
> +begin
set option usrprf = *user, dynusrprf = *user, commit = *none

2024-08-06 19:20 UTC, forstie commented on src/install.sql
> +begin
set option usrprf = *user, dynusrprf = *user, commit = *none

2024-08-06 19:21 UTC, forstie commented on src/install.sql
> +modifies sql data
set option usrprf = *user, dynusrprf = *user, commit = *none

2024-08-06 19:21 UTC, forstie commented on src/install.sql
> +modifies sql data
set option usrprf = *user, dynusrprf = *user, commit = *none

2024-08-07 02:52 UTC, worksofliam commented on src/auth.sql
> +  renew:
Correct. Not needed.

2024-08-07 02:53 UTC, worksofliam commented on src/generate.sql
> +  not deterministic
Added

2024-08-07 02:56 UTC, worksofliam commented on src/auth.sql
> +  not deterministic
Done

2024-08-07 02:56 UTC, worksofliam commented on src/install.sql
> +create or replace variable watsonx.spaceid varchar(100) default '';
Done

2024-08-07 02:57 UTC, worksofliam commented on src/install.sql
> +create or replace variable watsonx.JobBearerToken varchar(10000) default null;
Done

2024-08-07 02:57 UTC, worksofliam commented on src/install.sql
> +begin
Done

2024-08-07 02:58 UTC, worksofliam commented on src/install.sql
> +modifies sql data
Done

2024-08-07 14:30 UTC, forstie reviewed
new comments for Liam to consider

2024-08-07 16:47 UTC, worksofliam commented on src/auth.sql
> +create or replace function watsonx.authenticate()
Please make an issue out of this. I agree they're good, but don't belong in this PR.

2024-08-07 16:49 UTC, worksofliam commented on src/install.sql
> +  returns char(1)
Not applicable on this function it seems.

2024-08-07 16:51 UTC, worksofliam commented on src/auth.sql
> +create or replace function watsonx.authenticate()
I made an issue! #6

2024-08-07 17:26 UTC, forstie approved these changes
good

2024-08-07 17:44 UTC, merged